apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-task-assignment-1
spec:
  steps:
  - name: retrieve-yaml
    Image: quay.io/ibmgaragecloud/alpine-curl
    script: |
      mkdir -p /workspace/k8s | cd /workspace/k8s | curl -o /workspace/run-steps-as-non-root.yaml https://raw.githubusercontent.com/tektoncd/pipeline/main/examples/v1beta1/taskruns/run-steps-as-non-root.yaml 
  - name: extract-task
    Image: quay.io/ibmgaragecloud/alpine-curl
    script: |
      cd /workspace/k8s | head -24 /workspace/run-steps-as-non-root.yaml >> /workspace/run-steps-as-non-root-task-only.yaml
  - name: swap-image
    Image: quay.io/ibmgaragecloud/alpine-curl
    script: |
      sed 's+ubuntu+quay.io/ibmgaragecloud/alpine-curl+g' /workspace/run-steps-as-non-root.yaml >> /workspace/run-steps-as-non-root-alpine-task.yaml